RC_XXX(RC_OK,0)

RC_XXX(RC_NULL,-1)
RC_XXX(RC_MALLOC,-2)
RC_XXX(RC_BUFOVERFLOW,-3)
RC_XXX(RC_ARG,-4)
RC_XXX(RC_INTERNAL,-9)

RC_XXX(RC_VERSION,-20)
RC_XXX(RC_AUTH_TOPIC,-21)
RC_XXX(RC_AUTH_SIGNATURE,-22)

RC_XXX(RC_TOPIC,-30)
RC_XXX(RC_SIGNATURE,-31)
RC_XXX(RC_LOCATION,-32)
RC_XXX(RC_SHARD,-33)

RC_XXX(RC_INSUFFICIENT,-40)
RC_XXX(RC_MESSAGE,-41)

RC_XXX(RC_MARKER,-999)
