RC_XXX(RC_OK,0)

RC_XXX(RC_NULL,-1)
RC_XXX(RC_MALLOC,-2)
RC_XXX(RC_BUFOVERFLOW,-3)
RC_XXX(RC_ARG,-4)
RC_XXX(RC_INSUFFICIENT,-5)
RC_XXX(RC_PRIVATEKEY,-6)

RC_XXX(RC_VERSION,-20)
RC_XXX(RC_TOPIC,-21)
RC_XXX(RC_SIGNATURE,-22)
RC_XXX(RC_LOCATION,-32)
RC_XXX(RC_SHARD,-24)
RC_XXX(RC_MESSAGE,-25)

RC_XXX(RC_DEMO_7K_7L_63C,-50)

RC_XXX(RC_INTERNAL,-64)
RC_XXX(RC_MARKER,-127)
