package com.tereslogica.arcanacard;

/**
 * Created by john on 27/11/14.
 */
public class ConstShakespeare {

    public final static String author = "Shakespeare";
    public final static String quotes[] = {
            "Hamlet", "To be not to be that is the question", "Shakespeare: Act III Scene I",
            "*", "Neither a borrower nor a lender be; For loan oft loses both itself and friend, and borrowing dulls the edge of husbandry", "Shakespeare: Act I Scene III",
            "*", "This above all: to thine own self be true", "Shakespeare: Act I Scene III",
            "*", "Though this be madness, yet there is method in't.", "Shakespeare: Act II Scene II",
            "*", "That it should come to this!", "Shakespeare: Act I Scene II",
            "*", "There is nothing either good or bad, but thinking makes it so", "Shakespeare: Act II Scene II",
            "*", "What a piece of work is man! How noble in reason! How infinite in faculty! In form and moving how express and admirable!", "Shakespeare: Act II Scene II",
            "*", "In action how like an angel! In apprehension how like a god! The beauty of the world, the paragon of animals!", "Shakespeare: Act II Scene II",
            "*", "The lady doth protest too much, methinks", "Shakespeare: Act III Scene II",
            "*", "In my mind's eye", "Shakespeare: Act I Scene II",
            "*", "Shakespeare: A little more than kin, and less than kind", "Shakespeare: Act I Scene II",
            "*", "The play's the thing wherein I'll catch the conscience of the king", "Shakespeare: Act II Scene II",
            "*", "Shakespeare: And it must follow, as the night the day, thou canst not then be false to any man", "Shakespeare: Act I Scene III",
            "*", "This is the very ecstasy of love", "Shakespeare: Act II Scene I",
            "*", "Brevity is the soul of wit", "Shakespeare: Act II Scene II",
            "*", "Doubt that the sun doth move, doubt truth to be a liar, but never doubt I love", "Shakespeare: Act II Scene II",
            "*", "Rich gifts wax poor when givers prove unkind", "Shakespeare: Act III Scene I",
            "*", "Do you think I am easier to be played on than a pipe?", "Shakespeare: Act III Scene II",
            "*", "I will speak daggers to her, but use none", "Shakespeare: Act III Scene II",
            "*", "When sorrows come, they come not single spies, but in battalions", "Shakespeare: Act IV Scene V",
            "As You Like It", "Shakespeare: All the world's a stage, and all the men and women merely players.", "Shakespeare: Act II Scene VII",
            "*", "They have their exits and their entrances; And one man in his time plays many parts", "Shakespeare: Act II Scene VII",
            "*", "Can one desire too much of a good thing?", "Shakespeare: Act IV Scene I",
            "*", "I like this place and willingly could waste my time in it", "Shakespeare: Act II Scene IV",
            "*", "How bitter a thing it is to look into happiness through another man's eyes!", "Shakespeare: Act V Scene II",
            "*", "Blow, blow, thou winter wind! Thou art not so unkind as man's ingratitude", "Shakespeare: Act II Scene VII",
            "*", "True is it that we have seen better days", "Shakespeare: Act II Scene VII",
            "*", "For ever and a day", "Shakespeare: Act IV Scene I",
            "*", "The fool doth think he is wise, but the wise man knows himself to be a fool", "Shakespeare: Act V Scene I",
            "King Richard III", "Now is the winter of our discontent", "Shakespeare: Act I Scene I",
            "*", "Shakespeare: A horse! a horse! my kingdom for a horse!", "Shakespeare: Act V Scene IV",
            "*", "Conscience is but a word that cowards use, devised at first to keep the strong in awe", "Shakespeare: Act V Scene III",
            "*", "So wise so young, they say, do never live long", "Shakespeare: Act III Scene I",
            "*", "Off with his head!", "Shakespeare: Act III Scene IV",
            "*", "Shakespeare: An honest tale speeds best, being plainly told", "Shakespeare: Act IV Scene IV",
            "*", "The king's name is a tower of strength", "Shakespeare: Act V Scene III",
            "*", "The world is grown so bad, that wrens make prey where eagles dare not perch", "Shakespeare: Act I Scene III",
            "Romeo and Juliet", "O Romeo, Romeo! wherefore art thou Romeo?", "Shakespeare: Act II Scene II",
            "*", "It is the east, and Juliet is the sun", "Shakespeare: Act II Scene II",
            "*", "Good Night, Good night! Parting is such sweet sorrow, that I shall say good night till it be morrow.", "Shakespeare: Act II Scene II",
            "*", "What's in a name? That which we call a rose by any other name would smell as sweet", "Shakespeare: Act II Scene II",
            "*", "Wisely and slow; they stumble that run fast", "Shakespeare: Act II Scene III",
            "*", "Tempt not a desperate man", "Shakespeare: Act V Scene III",
            "*", "For you and I are past our dancing days", "Shakespeare: Act I Scene V",
            "*", "O! she doth teach the torches to burn bright", "Shakespeare: Act I Scene V",
            "*", "It seems she hangs upon the cheek of night like a rich jewel in an Ethiope's ear", "Shakespeare: Act I Scene V",
            "*", "See, how she leans her cheek upon her hand! O that I were a glove upon that hand, that I might touch that cheek!", "Shakespeare: Act II Scene II",
            "*", "Not stepping o'er the bounds of modesty", "Shakespeare: Act IV Scene II",
            "Merchant of Venice", "But love is blind, and lovers cannot see", "Shakespeare: Act II Scene VII",
            "*", "If you prick us, do we not bleed? if you tickle us, do we not laugh? if you poison us, do we not die? and if you wrong us, shall we not revenge?", "Shakespeare: Act III Scene I",
            "*", "The devil can cite Scripture for his purpose", "Shakespeare: Act I Scene III",
            "*", "I like not fair terms and a villain's mind", "Shakespeare: Act I Scene III",
            "Merry Wives of Windsor", "Why, then the world's mine oyster", "Shakespeare: Act II Scene II",
            "*", "This is the short and the long of it", "Shakespeare: Act II Scene II",
            "*", "I cannot tell what the dickens his name is", "Shakespeare: Act III Scene II",
            "*", "Shakespeare: As good luck would have it", "Shakespeare: Act III Scene V",
            "Measure for Measure", "Our doubts are traitors, and make us lose the good we oft might win, by fearing to attempt", "Shakespeare: Act I Scene IV",
            "*", "Some rise by sin, and some by virtue fall", "Shakespeare: Act II Scene I",
            "*", "The miserable have no other medicine but only hope", "Shakespeare: Act III Scene I",
            "King Henry IV", "He will give the devil his due", "Shakespeare: Act I Scene II",
            "*", "The better part of valour is discretion", "Shakespeare: Act V Scene IV",
            "*", "He hath eaten me out of house and home", "Shakespeare: Act II Scene I",
            "*", "Uneasy lies the head that wears a crown", "Shakespeare: Act III Scene I",
            "*", "Shakespeare: A man can die but once", "Shakespeare: Act III Scene II",
            "*", "I do now remember the poor creature, small beer", "Shakespeare: Act II Scene II",
            "*", "We have heard the chimes at midnight", "Shakespeare: Act III Scene II",
            "*", "The smallest worm will turn, being trodden on", "Shakespeare: Act II Scene II",
            "*", "Suspicion always haunts the guilty mind; The thief doth fear each bush an officer", "Shakespeare: Act V Scene VI",
            "*", "Delays have dangerous ends", "Shakespeare: Act III Scene II",
            "*", "Of all base passions, fear is the most accursed", "Shakespeare: Act V Scene II",
            "*", "The first thing we do, let's kill all the lawyers", "Shakespeare: Act IV Scene II",
            "*", "Small things make base men proud", "Shakespeare: Act IV Scene I",
            "*", "True nobility is exempt from fear", "Shakespeare: Act IV Scene I",
            "*", "Having nothing, nothing can he lose", "Shakespeare: Act III Scene III",
            "Taming of the Shrew", "I'll not budge an inch", "Induction Scene I",
            "Timon of Athens", "We have seen better days", "Shakespeare: Act IV Scene II",
            "Julius Caesar", "Friends, Romans, countrymen, lend me your ears; I come to bury Caesar, not to praise him", "Shakespeare: Act III Scene II",
            "*", "But, for my own part, it was Greek to me", "Shakespeare: Act I Scene II",
            "*", "Shakespeare: A dish fit for the gods", "Shakespeare: Act II Scene I",
            "*", "Cry Havoc, and let slip the dogs of war!", "Shakespeare: Act III Scene I",
            "*", "Et tu, Brute!", "Shakespeare: Act III Scene I",
            "*", "Men at some time are masters of their fates: The fault, dear Brutus, is not in our stars, but in ourselves, that we are underlings", "Shakespeare: Act I Scene II",
            "*", "Not that I loved Caesar less, but that I loved Rome more", "Shakespeare: Act III Scene II",
            "*", "Beware the ides of March", "Shakespeare: Act I Scene II",
            "*", "This was the noblest Roman of them all", "Shakespeare: Act V Scene V",
            "*", "When that the poor have cried, Caesar hath wept: Ambition should be made of sterner stuff", "Shakespeare: Act III Scene II",
            "*", "Yond Cassius has a lean and hungry look; He thinks too much: such men are dangerous", "Shakespeare: Act I Scene II",
            "*", "For Brutus is an honourable man; So are they all, all honourable men", "Shakespeare: Act III Scene II",
            "*", "Shakespeare: As he was valiant, I honor him; but, as he was ambitious, I slew him", "Shakespeare: Act III Scene II",
            "*", "Cowards die many times before their deaths; The valiant never taste of death but once.", "Shakespeare: Act II Scene II",
            "*", "Of all the wonders that I yet have heard, it seems to me most strange that men should fear; Seeing that death, a necessary end, will come when it will come", "Shakespeare: Act II Scene II",
            "Macbeth", "There's daggers in men's smiles", "Shakespeare: Act II Scene III",
            "*", "what's done is done", "Shakespeare: Act III Scene II",
            "*", "I dare do all that may become a man; Who dares do more is none", "Shakespeare: Act I Scene VII",
            "*", "Fair is foul, and foul is fair", "Shakespeare: Act I Scene I",
            "*", "I bear a charmed life", "Shakespeare: Act V Scene VIII",
            "*", "Yet do I fear thy nature; It is too full o' the milk of human kindness.", "Shakespeare: Act I Scene V",
            "*", "Will all great Neptune's ocean wash this blood clean from my hand? No, this my hand will rather the multitudinous seas incarnadine, making the green one red", "Shakespeare: Act II Scene II",
            "*", "Double, double toil and trouble; Fire burn, and cauldron bubble.", "Shakespeare: Act IV Scene I",
            "*", "Out, damned spot! out, I say!", "Shakespeare: Act V Scene I",
            "*", "Shakespeare: All the perfumes of Arabia will not sweeten this little hand.", "Shakespeare: Act V Scene I",
            "*", "When shall we three meet again in thunder, lightning, or in rain? When the hurlyburly 's done, When the battle 's lost and won", "Shakespeare: Act I Scene I",
            "*", "If chance will have me king, why, chance may crown me", "Shakespeare: Act I Scene III",
            "*", "Nothing in his life became him like the leaving it; he died as one that had been studied in his death to throw away the dearest thing he owed, as t'were a careless trifle", "Shakespeare: Act I Scene IV",
            "*", "Look like the innocent flower, but be the serpent under 't.", "Shakespeare: Act I Scene V",
            "*", "I have no spur to prick the sides of my intent, but only vaulting ambition, which o'erleaps itself, and falls on the other.", "Shakespeare: Act I Scene VII",
            "*", "Is this a dagger which I see before me, The handle toward my hand?", "Shakespeare: Act II Scene I",
            "*", "Life's but a walking shadow, a poor player that struts and frets his hour upon the stage and then is heard no more", "Shakespeare: Act V Scene V",
            "*", "It is a tale told by an idiot, full of sound and fury, signifying nothing.", "Shakespeare: Act V Scene V",
            "King Lear", "How sharper than a serpent's tooth it is to have a thankless child!", "Shakespeare: Act I Scene IV",
            "*", "I am a man more sinned against than sinning", "Shakespeare: Act III Scene II",
            "*", "My love's more richer than my tongue", "Shakespeare: Act I Scene I",
            "*", "Nothing will come of nothing.", "Shakespeare: Act I Scene I",
            "*", "Have more than thou showest, speak less than thou knowest, lend less than thou owest", "Shakespeare: Act I Scene IV",
            "*", "The worst is not, So long as we can say, 'This is the worst.' ", "Shakespeare: Act IV Scene I",
            "Othello", "T’is neither here nor there.", "Shakespeare: Act IV Scene III",
            "*", "I will wear my heart upon my sleeve for daws to peck at", "Shakespeare: Act I Scene I",
            "*", "To mourn a mischief that is past and gone is the next way to draw new mischief on", "Shakespeare: Act I Scene III",
            "*", "The robbed that smiles steals something from the thief", "Shakespeare: Act I Scene III",
            "Antony and Cleopatra", "My salad days, when I was green in judgment.", "Shakespeare: Act I Scene V",
            "Cymbeline", "The game is up.", "Shakespeare: Act III Scene III",
            "*", "I have not slept one wink.", "Shakespeare: Act III Scene III",
            "Twelfth Night", "Be not afraid of greatness: some are born great, some achieve greatness and some have greatness thrust upon them", "Shakespeare: Act II Scene V",
            "*", "Love sought is good, but giv'n unsought is better", "Shakespeare: Act III Scene I",
            "King Henry V", "Men of few words are the best men", "Shakespeare: Act III Scene II",
            "Midsummer Night's Dream", "The course of true love never did run smooth", "Shakespeare: Act I Scene I",
            "*", "Love looks not with the eyes, but with the mind, and therefore is winged Cupid painted blind", "Shakespeare: Act I Scene I",
            "Much Ado About Nothing", "Everyone can master a grief but he that has it", "Shakespeare: Act III Scene II",
            "Titus Andronicus", "These words are razors to my wounded heart", "Shakespeare: Act I Scene I",
            "Winter's Tale", "What's gone and what's past help should be past grief", "Shakespeare: Act III Scene II",
            "*", "You pay a great deal too dear for what's given freely", "Shakespeare: Act I Scene I",
            "Taming of the Shrew", "I snatched one half out of the jaws of death", "Shakespeare: Act III Scene IV",
            "*", "Thus the whirligig of time brings in his revenges", "Shakespeare: Act V Scene I",
            "*", "For the rain it raineth every day", "Shakespeare: Act V Scene I",
    };
};
